### ISSUE TITLE
Plugin disables Sublime's search case sensitivity toggle shortcut

### ISSUE THREAD

**Issue by dgirgenti** [pichillilorenzo/JavaScriptEnhancements#36]
### Expected Behavior
Pressing `cmd+alt+c` in search toggles the search "Case Sensitive" button.

### Actual Behavior
Pressing `cmd+alt+c` in search does nothing.

### Steps to Reproduce the Problem

1. Install Javascript Enhancements
1. `cmd+f` or `cmd+shift+f `to open search
1. Try to toggle Case Sensitivity with `cmd+alt+c`
1. See that nothing happens
1. Uninstall Javascript Enhancements
1. See that the shortcut works again

### Specifications

- Sublime Text 3 build: 3.0, 31143
- OS: macOS 10.12.6
- JavaScript Enhancements version: 0.15.0

**Comment by pichillilorenzo** [comment]
mmm ok that's because I defined a keymap with this key binding. I will change it with something else in the next release! A quick workaround for now is: go to `Preferences > Package Settings > JavaScript Enhancements > Key Bindings` and then put this setting:
```json
[
  {
    "keys": ["here the new key binding"],
    "command": "javascript_enhancements_navigate_flow_errors",
    "args": {
      "type":  "next"
    }
  }
]
``` 
change "here the new key binding" with another key binding (now is `"super+alt+c"`).
