### ISSUE TITLE
Keywords sensitive issues

### ISSUE THREAD

**Issue by icepole-jon** [pichillilorenzo/JavaScriptEnhancements#39]
can It be 'not case sensitive' ?
When I use '.toF', the suggestion shows good with 'toFixed',
but when I use '.tof' It's does't work...

**Comment by pichillilorenzo** [comment]
It is weird because it is already working:
<img width="436" alt="schermata 2018-03-05 alle 08 40 13" src="https://user-images.githubusercontent.com/5956938/36962903-9b92d6a4-2051-11e8-8c8b-e4b0be5e47e7.png">

I don't think this problem is caused by my plugin because there is no way to specify the case (sensitive or insensitive). Sublime Text treats already the completions using case insensitive! So maybe it could be a Sublime Text 3 issue.

**Comment by icepole-jon** [comment]
@pichillilorenzo yep, I am using a lot of plugin together, It may be a conflict 😂 thx
