### ISSUE TITLE
Interoperability with sublimelinter

### ISSUE THREAD

**Issue by nejsimon** [pichillilorenzo/JavaScriptEnhancements#47]
It would be nice if Javascript Enhancements could be used together with SublimeLinter!

When a linter detects an error it will properly mark the code block in red but when hovering it you get something nonsensical from JavascriptEnhancements and not the expected tooltip message from SublimeLinter detailing the error. You can still see the error in the status field when placing the cursor in the code block though.

### Expected Behavior
The linter error is shown when hovering the code.

### Actual Behavior
A nonsensical message i shown

### Sublime Text console logs 
No errors in the log

### Screenshots
SublimeLinter, JavaScriptEnhancements enabled
![enabled](https://user-images.githubusercontent.com/770893/38860440-7cd1cb34-4230-11e8-919d-40367766ecf2.png)
SublimeLinter enabled, JavaScriptEnhancements disabled
![disabled](https://user-images.githubusercontent.com/770893/38860444-7f6453da-4230-11e8-8d0b-5ef6e08c62a3.png)

### Steps to Reproduce the Problem

1. Install SublimeLinter and  a linter plugin for js files
2. Install JavascriptEnhancements
3. Write some broken code
4. Hover the broken code when the linter detects the error

### Specifications

- Sublime Text 3 build: 3143
- OS: Windows 7 x64
- JavaScript Enhancements version: 0.6.12

**Comment by pichillilorenzo** [comment]
It's weird because this souldn't happen.. In this case you should see a red popup from the flow linter saying that it's an error.. Maybe there are some problems with async functions

**Comment by pichillilorenzo** [comment]
Ah no sorry, you aren't in a JavaScript project, so you need to active the flow linter! See here https://github.com/pichillilorenzo/JavaScriptEnhancements/wiki/Errors-and-linting

**Comment by monovertex** [comment]
I'm encountering a similar issue, as I'm using SublimeLinter as well, with ESlint. I don't need or plan to use flow lint. In my case, this plugin overrides the tooltip displayed by SublimeLinter.

With JSE enabled:
![image](https://user-images.githubusercontent.com/1837605/39057413-d1242586-44c1-11e8-8cb4-7a6fdb34d0c5.png)
![image](https://user-images.githubusercontent.com/1837605/39057424-d98a3526-44c1-11e8-9fdf-ceba3a1f0e41.png)

With JSE disabled:
![image](https://user-images.githubusercontent.com/1837605/39057457-f0335df2-44c1-11e8-87a1-000c922c5993.png)

It would be nice if we could set a level of priority, so that the SublimeLinter tooltip would have higher priority if needed, as I figure displaying both of them would be too complicated.

**Comment by nejsimon** [comment]
That's my situation as well. We have a bunch of eslint rules including a few custom ones to enforce our code conventions so I can't switch to flow even though there might be advantages.

**Comment by pichillilorenzo** [comment]
I will check about that :+1:

**Comment by pichillilorenzo** [comment]
Try the new version 0.16.14! Now it should work.

**Comment by nejsimon** [comment]
It seems to be working! Thanks a lot!

**Comment by ahmadsholehin** [comment]
I seem to have this issue. Using 0.16.20, Sublime 3.2.

JSE is blocking SublimeLinter's tooltips when hovering regions.
