### ISSUE TITLE
Autocompletion tooltip stutters

### ISSUE THREAD

**Issue by lukakerr** [pichillilorenzo/JavaScriptEnhancements#5]
The autocompletion tooltip is a bit stuttery and seems to popup twice during autocompletion. See the video below:

https://streamable.com/jnbyf

Not that big of an issue, but mildly annoying when typing. Awesome job on the package though!

**Comment by pichillilorenzo** [comment]
@lukakerr yeah I know about that, but the problem is that I get the autocompletion list from the Flow server, so in order to do it in a non-blocking way, I do it using async functions.. The problem is that I can't block the default popup from showing 😞. I will try to do something about that.. I need to think how to do it!

However thank you! 😄

**Comment by pichillilorenzo** [comment]
@lukakerr I updated the plugin! Try the new release and let me know if now it is better or not.

**Comment by lukakerr** [comment]
Just checked it, looks much better! No more stuttering. Cheers

**Comment by webcoder31** [comment]
Hello!
I'm experimenting the same issue with the latest version too (just installed today), using ST3 on Win 7. The autocomplete popup is quickly flickering which make it impossible to select an item because it systematically reset the selection to the top most item. Is there any chance to solve this ?
By the way, thank you for the incredible work you've done and you share with all others.
Best regards

**Comment by john-behan** [comment]
@webcoder31 do you have the Typescriptplugin installed?

This was the issue for me - fixed it by setting these two options in User settings

```
"enable_language_service_for_javascript": false,
"enable_typescript_language_service": false,
```

**Comment by webcoder31** [comment]
@john-behan Hi, Yes, I have the Typescript plugin installed. Now, it just works fine with the given options. Thank you very much !
