### ISSUE TITLE
Just installed from package manager but getting flow error

### ISSUE THREAD

**Issue by benonymus** [pichillilorenzo/JavaScriptEnhancements#63]
### Expected Behavior
Starting

### Actual Behavior
giving error

### Sublime Text console logs 
Wrong version of Flow. The config specifies version ^0.67.0 but this is version 0.74.0
Could not start Flow server!

### Steps to Reproduce the Problem

1. install from package manager

### Specifications

- Sublime Text 3 build: 3176
- OS: windows 10
- JavaScript Enhancements version: 2.6.99

**Comment by benonymus** [comment]
it is the same if I install it manually

**Comment by pichillilorenzo** [comment]
Because, like the message itself say, the flow version is wrong. You have specified in your .flowconfig file a different version, but the plugin works with the 0.74.0   version.
If you want to work specifily with the 0.67.0 version, then you need to install it locally, in your project, and reference it in `flow_cli_custom_path` of the `project_settings.json` file (https://github.com/pichillilorenzo/JavaScriptEnhancements/wiki/Project-settings)

Moreover the version of the plugin that you specified is incorrect: 2.6.99 is the version of the JavaScript Completion plugin and not of this new one!

**Comment by benonymus** [comment]
oh thanks :D
